"""Shared paper-trade wire-format models.

Used by ATLAS routes (read/publish) and PROMETHEUS executor (subscribe/ack).
Lives in atlas/models/ so neither side imports from the other.
PROMETHEUS imports these too — update its import path in the same PR.
"""
from __future__ import annotations

from datetime import datetime
from decimal import Decimal
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field


SignalSide = Literal["LONG", "SHORT", "CLOSE"]


class DemoSymbol(BaseModel):
    """A single Bitget demo-tradeable contract."""
    model_config = ConfigDict(frozen=True)

    symbol: str          # the demo symbol Bitget executes against, e.g. "SBTCSUSDT"
    base_symbol: str     # the canonical symbol POLARIS speaks in, e.g. "BTCUSDT"
    margin_coin: str     # e.g. "SUSDT"
    contract_type: str   # e.g. "SUSDT-FUTURES"
    fetched_at: datetime  # UTC, tz-aware


class PaperTradeInstruction(BaseModel):
    """The payload published on `polaris:paper_trade:{base_symbol}`.

    SCHEMA VERSION 1.0.0 — bump major when removing fields, minor when
    adding optional fields. PROMETHEUS rejects unknown major versions.
    """
    model_config = ConfigDict(frozen=True)

    schema_version: str = "1.0.0"
    order_id: str             # uuid4 hex generated by ATLAS
    base_symbol: str          # e.g. "BTCUSDT"
    demo_symbol: str          # e.g. "SBTCSUSDT"
    margin_coin: str          # e.g. "SUSDT"
    side: SignalSide
    size_usd_notional: Decimal = Field(..., gt=Decimal("0"))
    leverage: int = Field(..., ge=1, le=125)
    requested_at: datetime    # UTC, tz-aware — set by ATLAS
    source: str               # e.g. "manual_paper_trade", "atlas_signal"


class PaperTradeAck(BaseModel):
    """Result of an instruction execution attempt. Published back on
    `polaris:paper_trade:ack:{order_id}` for ATLAS / dashboard to consume."""
    model_config = ConfigDict(frozen=True)

    schema_version: str = "1.0.0"
    order_id: str
    status: Literal["accepted", "rejected", "executed", "failed"]
    bitget_order_id: str | None = None
    reason: str | None = None
    acknowledged_at: datetime
